name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Install Nuclei
        run: |
          go install github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
      - name: Update Nuclei Templates
        run: nuclei -update-templates
      - name: Run Nuclei Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: "testphp.vulnweb.com"
