name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run Nuclei with full output
      uses: projectdiscovery/nuclei-action@main
      with:
        target: "testphp.vulnweb.com"
        flags: "-debug"
