name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Nuclei
        run: |
          sudo apt update
          sudo apt install -y nuclei
      - name: Update Nuclei Templates
        run: nuclei -update-templates
      - name: Run Nuclei Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: "testphp.vulnweb.com"
